const CLIENTS_API = `http://${window.location.hostname || '127.0.0.1'}:3000/api/clients`;
const clientsList = document.getElementById('clientsList'); const clientsSearch = document.getElementById('clientsSearch'); const clientsEmpty = document.getElementById('clientsEmptyState'); const clientDialog = document.getElementById('clientDialog'); const clientDialogContent = document.getElementById('clientDialogContent'); let searchTimer;
const labels = { pending:'Pendente', confirmed:'Confirmado', in_progress:'Em atendimento', completed:'Concluído', cancelled:'Cancelado', no_show:'Não compareceu' };
const esc = (value='') => { const element=document.createElement('div'); element.textContent=value ?? ''; return element.innerHTML; };
const currency = (value) => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);
const dateLabel = (value) => new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'});
async function api(path='', options={}) { const response=await fetch(`${CLIENTS_API}${path}`,{headers:{'Content-Type':'application/json'},...options}); const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.error || 'Não foi possível concluir a operação.'); return data; }
async function loadClients() { try { const clients=await api(`?q=${encodeURIComponent(clientsSearch.value.trim())}`); clientsList.replaceChildren(); clientsEmpty.hidden=clients.length>0; clients.forEach((client)=>{const next=client.next_appointment ? client.next_appointment.split('|') : null; const row=document.createElement('tr'); row.innerHTML=`<td data-label="Nome">${esc(client.name)}</td><td data-label="Telefone">${esc(client.phone)}</td><td data-label="E-mail">${esc(client.email || 'Não informado')}</td><td data-label="Próximo">${next ? `${dateLabel(next[0])}<br><small>${next[1]} · ${esc(next[2])}</small>` : 'Sem agendamento'}</td><td data-label="Cancelamentos"><span class="client-count">${client.cancellations}</span></td><td data-label="Faltas"><span class="client-count">${client.no_shows}</span></td><td data-label=""><button class="appointment-action" data-client-id="${client.id}">Ver perfil</button></td>`; clientsList.append(row);}); } catch(error) { clientsEmpty.hidden=false; clientsEmpty.textContent=error.message; } }
function openDialog(content){clientDialogContent.innerHTML=content;clientDialog.showModal();} function closeDialog(){if(clientDialog.open)clientDialog.close();}
async function profile(id){try{const client=await api(`/${id}`);const history=client.appointments.map((item)=>`<div class="client-history-item"><div><strong>${esc(item.service_name)}</strong><br><small>${dateLabel(item.date)} · ${item.start_time} – ${item.end_time}</small></div><span class="status-badge status-${item.status}">${labels[item.status]}</span></div>`).join('')||'<p class="service-empty-state">Nenhum agendamento no histórico.</p>';openDialog(`<div class="client-profile-head"><h2>${esc(client.name)}</h2><p>${esc(client.phone)} · ${esc(client.email || 'E-mail não informado')}</p><div class="appointment-details"><div><dt>Próximo atendimento</dt><dd>${client.next_appointment ? `${dateLabel(client.next_appointment.date)} às ${client.next_appointment.start_time}` : 'Não há'}</dd></div><div><dt>Cancelamentos</dt><dd>${client.cancellations}</dd></div><div><dt>Não compareceu</dt><dd>${client.no_shows}</dd></div></div></div><div class="client-history"><h3>Histórico de agendamentos</h3>${history}</div>`);}catch(error){alert(error.message);}}
function newClientForm(){openDialog(`<h2>Nova cliente</h2><form class="client-form" id="clientForm"><div><label>Nome</label><input id="clientName" required></div><div><label>Telefone</label><input id="clientPhone" required></div><div><label>E-mail</label><input id="clientEmail" type="email"></div><button class="admin-button" type="submit">Cadastrar cliente</button><p class="client-feedback" id="clientFeedback"></p></form>`);document.getElementById('clientForm').addEventListener('submit',async(event)=>{event.preventDefault();try{await api('',{method:'POST',body:JSON.stringify({name:document.getElementById('clientName').value,phone:document.getElementById('clientPhone').value,email:document.getElementById('clientEmail').value})});closeDialog();loadClients();}catch(error){document.getElementById('clientFeedback').textContent=error.message;}});}
clientsSearch.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(loadClients,250);});clientsList.addEventListener('click',(event)=>{const button=event.target.closest('[data-client-id]');if(button)profile(button.dataset.clientId);});document.getElementById('newClientButton').addEventListener('click',newClientForm);document.getElementById('clientDialogClose').addEventListener('click',closeDialog);document.querySelectorAll('[data-theme-toggle]').forEach((button)=>button.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('smf-theme',next);}));const sidebar=document.getElementById('clientsSidebar'),toggle=document.getElementById('clientsMenuToggle'),backdrop=document.getElementById('clientsBackdrop');function menu(open){sidebar.classList.toggle('is-open',open);toggle.classList.toggle('is-open',open);backdrop.classList.toggle('is-visible',open);}toggle.addEventListener('click',()=>menu(!sidebar.classList.contains('is-open')));backdrop.addEventListener('click',()=>menu(false));loadClients();
